### ISSUE TITLE
Badges should be forced to have unique names

### ISSUE THREAD

**Issue by alyssadelaine** [developmentseed/scoreboard#189]
Currently I can create two "Consistency" badges, which is confusing and not the desired behavior

**Comment by kamicut** [comment]
@sethvincent I wanted to enforce a uniqueness constraint on createBadge or editBadge. The problem is that right now errors are being swallowed by the notification system in the store. So if we wanted to catch a postgres error for violating the uniqueness constraint, the form would still go through but a notification would pop up with the error.

https://github.com/developmentseed/scoreboard/blob/94ebdafb98a7efb8e44a08345a6c1f1f98514079/lib/store/actions/badges.js#L30-L39

Where do you think we should catch the error? Possibilities are in the model code, the route code, the frontend store or even dynamically while typing the badge name.

**Comment by sethvincent** [comment]
I'd probably do a combination of catching it on the server side and making sure the error message there is clear, then catching it in the store in the frontend side to show the notification and make sure the user stays on the form.

Checking it while typing would be cool also and might be implemented differently. The simplest method might be to send a get request to see if there's a badge with that name already.
