### ISSUE TITLE
Lag in retrieving campaign data

### ISSUE THREAD

**Issue by alyssadelaine** [developmentseed/scoreboard#321]
Campaign cards are showing up before data is retrieved, so when a user clicks on a card they get the following error

![Screen Shot 2019-03-18 at 1 30 29 PM](https://user-images.githubusercontent.com/6155420/54550260-0fbafe80-4982-11e9-9434-254d4140f915.png)

**Comment by kamicut** [comment]
This happens when there is a campaign in the tasking manager, but there is no edits with the hashtag of the campaign. So we cannot display any statistics related to the hashtag. We should display only the campaign metadata. @LanesGood should we have a banner or something? Or show zeros for all the records?

**Comment by LanesGood** [comment]
@kamicut so there are no changesets tagged with the hashtag yet for the campaign but the campaign exists? I agree that we should display the campaign metadata, and return the normal campaign page. The banner can then be displayed above the "Scoreboard panel," or in the table itself  if we are unable to add another element to the layout.

**Comment by alyssadelaine** [comment]
This was resolved
