### ISSUE TITLE
Add a user's member and moderated teams to Teams page when signed in + connected

### ISSUE THREAD

**Issue by LanesGood** [developmentseed/scoreboard#503]
When a user has !) signed into Scoreboard and 2) connected the Teams application (via #501) the main Teams index page should contain three tables: All Teams (public), `My Teams`, and `Teams Moderating`

![TeamsIndex_A0](https://user-images.githubusercontent.com/12634024/74369812-06116500-4da4-11ea-94f2-565ee9ec288b.png)

**Comment by kamicut** [comment]
Would depend on implementing https://github.com/developmentseed/osm-teams/issues/145

**Comment by guidorice** [comment]
![74369812-06116500-4da4-11ea-94f2-565ee9ec288b](https://user-images.githubusercontent.com/766758/79483905-2346f780-7fd0-11ea-9281-f44121179141.png)

The mockup was a little confusing so after discussing, I am simplifying it by:

- removing Country filter. We do not currently have ability to filter teams by country (technically we could do a spatial join on the team location with all country boundaries, but that seems out of scope, and in that scenario be better just to store country as an ISO country code instead of a point).

- Removing  "teams you moderate" and "teams you belong to" tables because they are redundant with having the 2 same filters in the sidebar. We are adding the filters in the sidebar, and they will be hidden if the user is not authenticated.

cc @LanesGood @kamicut
