### ISSUE TITLE
Connect your Teams button -> Hydra Error: invalid_client

### ISSUE THREAD

**Issue by guidorice** [developmentseed/scoreboard#516]
@LanesGood and I both went through a from-scratch setup of scoreboard and osm-teams today, in parallel on both of our dev machines, and we both ran into this problem when hitting the Connect your Teams button from  the /teams page in Scoreboard:

The browser redirects to
http://localhost:4444/oauth2/fallbacks/error?error=invalid_client&error_description=Client+authentication+failed+%28e.g.%2C+unknown+client%2C+no+client+authentication+included%2C+or+unsupported+authentication+method%29&error_hint=The+requested+OAuth+2.0+Client+does+not+exist.

The error message shown is:

The OAuth2 request resulted in an error.

    Error: invalid_client
    Description: Client authentication failed (e.g., unknown client, no client authentication included, or unsupported authentication method)
    Hint: The requested OAuth 2.0 Client does not exist.
    Debug:

You are seeing this page because configuration key urls.error is not set.

If you are an administrator, please read the guide to understand what you need to do. If you are a user, please contact the administrator.

**Comment by guidorice** [comment]
@LanesGood when I reloaded  http://localhost:8989/clients to see my osm-teams list of clients, it was empty! Please check yours. Maybe there is a problem with osm-teams saving the client configuration.

This also would match the "unknown client" error message above.

I then re-created a new client in osm-teams, named scoreboard-dev, with the callback url: `http://localhost:8181/auth/teams/accept`. I then edited the scoreboard .env file with this keypair, and then I was able to complete "Connect your Teams" successfully.

If this solves your problem, and we both ran into it, I suspect the oAuth client is not successfully saved on osm-teams intermittently or perhaps the first time.

**Comment by LanesGood** [comment]
@guidorice my localhost:8989/clients shows the Scoreboard client I created on Friday....

I am also seeing my test team created in the local teams instance on Scoreboard, when not logged in.

After logging in, I successfully see the Connect Teams banner when I first navigate to the /teams path from the top navigation bar. I also see the available public local teams.

However, after navigating to the Homepage from the top nav, and then back to /teams, I _do not_ see the connect teams banner, nor do I see the local teams seen previously. The same is true when navigating to other pages via the navbar, and then back to /teams. In all cases, reloading the /teams page successfully exposes the "Connect Teams" banner and the local teams. 

So, this issue seems like a server vs. client side rendering issue, and unrelated to the oAuth invalid client issue.

**Comment by guidorice** [comment]
@LanesGood that confirms what I was seeing in #511 .

**Comment by LanesGood** [comment]
@guidorice in trying to set up teams again, I see the following error:
```
The OAuth2 request resulted in an error.
Error: invalid_request
Description: The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed
Hint: The "redirect_uri" parameter does not match any of the OAuth 2.0 Client's pre-registered redirect urls.
Debug:
You are seeing this page because configuration key urls.error is not set.
```
is this related to the same issue?

**Comment by guidorice** [comment]
@LanesGood this might happen if your callback url for the osm-teams new client is not

`http://localhost:8181/auth/teams/accept`

Can you double check that & create a new osm-teams client app for your scoreboard-dev?

**Comment by guidorice** [comment]
(We confirmed on a call that is the path he's using)

**Comment by guidorice** [comment]
@kamicut was able to get @LanesGood up and running in his development environment today. It might have been a database migration issue, or something that was resolved by more recent changes to develop branch. In any case, closing this now as 'cannot reproduce'.
